# These are my base versions for tools that I use regularly
[tools]
pnpm = "latest"
yarn = "1.22.19"
go = "latest"
rust = "latest"
neovim = "latest"
erlang = "latest"
rebar = "latest"
opam = "latest"
tmux = "3.4"
act = "latest"
hugo = "latest"
python = "3.9"
stack = "latest"
node = "latest"
gleam = "latest"
terraform = "latest"
opentofu = "latest"
