# These are my base versions for tools that I use regularly
[tools]
node = "latest"
pnpm = "latest"
yarn = "1.22.19"
go = "latest"
rust = "latest"
gleam = "latest"
neovim = "latest"
erlang = "latest"
rebar = "latest"
opam = "latest"
tmux = "3.4"
