#! /bin/bash
:: default : sketchybar --trigger skhd_mode_changed MODE=default
:: command : sketchybar --trigger skhd_mode_changed MODE=command
:: select : sketchybar --trigger skhd_mode_changed MODE=select
:: move : sketchybar --trigger skhd_mode_changed MODE=move
:: workspace : sketchybar --trigger skhd_mode_changed MODE=workspace
:: float : sketchybar --trigger skhd_mode_changed MODE=float

alt - space ; command
command, select, move, workspace, float < escape ; default

command < m ; move
command < w ; workspace
command < f ; float
command < s ; select
command < r : yabai -m space --rotate 90
command < 0 : yabai -m window --toggle zoom-fullscreen ; skhd -k "escape"
command < t : yabai -m window --toggle float ; skhd -k "escape"
command < e : yabai -m window --toggle split ; skhd -k "escape"
command < 0x18 : yabai -m space --balance ; skhd -k "escape"
command < x : yabai -m window --close ; skhd -k "escape"
select < h : yabai -m window --focus west
select < j : yabai -m window --focus south
select < k : yabai -m window --focus north
select < l : yabai -m window --focus east
move < h : yabai -m window --swap west
move < j : yabai -m window --swap south
move < k : yabai -m window --swap north
move < l : yabai -m window --swap east
float < e : yabai -m window --grid 1:3:0:1:2:1
float < t : yabai -m window --grid 1:3:1:1:2:1
float < d : yabai -m window --grid 1:3:0:1:1:1
float < f : yabai -m window --grid 1:3:1:1:1:1
float < g : yabai -m window --grid 1:3:2:1:1:1
float < return : yabai -m window --grid 1:1:0:0:1:1
workspace < 1 : yabai -m space --focus 1 ; skhd -k "escape"
workspace < 2 : yabai -m space --focus 2 ; skhd -k "escape"
workspace < 3 : yabai -m space --focus 3 ; skhd -k "escape"
workspace < 4 : yabai -m space --focus 4 ; skhd -k "escape"
workspace < 5 : yabai -m space --focus 5 ; skhd -k "escape"
workspace < 6 : yabai -m space --focus 6 ; skhd -k "escape"
workspace < 7 : yabai -m space --focus 7 ; skhd -k "escape"
workspace < 8 : yabai -m space --focus 8 ; skhd -k "escape"
workspace < 9 : yabai -m space --focus 9 ; skhd -k "escape"
workspace < 0 : yabai -m space --focus 10 ; skhd -k "escape"
workspace < ctrl - 1 : yabai -m window --space 1 ; skhd -k "escape"
workspace < ctrl - 2 : yabai -m window --space 2 ; skhd -k "escape"
workspace < ctrl - 3 : yabai -m window --space 3 ; skhd -k "escape"
workspace < ctrl - 4 : yabai -m window --space 4 ; skhd -k "escape"
workspace < ctrl - 5 : yabai -m window --space 5 ; skhd -k "escape"
workspace < ctrl - 6 : yabai -m window --space 6 ; skhd -k "escape"
workspace < ctrl - 7 : yabai -m window --space 7 ; skhd -k "escape"
workspace < ctrl - 8 : yabai -m window --space 8 ; skhd -k "escape"
workspace < ctrl - 9 : yabai -m window --space 9 ; skhd -k "escape"
workspace < ctrl - 0 : yabai -m window --space 10 ; skhd -k "escape"
workspace < h : yabai -m space --focus prev
workspace < l : yabai -m space --focus next
workspace < n : yabai -m window --space next ; skhd -k "escape"
workspace < p : yabai -m window --space prev ; skhd -k "escape"
workspace < c : yabai -m space --create ; skhd -k "escape"
workspace < x : yabai -m space --destroy ; skhd -k "escape"
