#! /bin/bash
# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

yabai -m config layout bsp
yabai -m config top_padding 8
yabai -m config bottom_padding 12
yabai -m config left_padding 16
yabai -m config right_padding 16
yabai -m config window_gap 8
yabai -m config window_shadow off
yabai -m config window_opacity on
yabai -m config normal_window_opacity 0.9
yabai -m config active_window_opacity 1.0
yabai -m config external_bar all:32:0

yabai -m rule --add app=".*" layer=normal
yabai -m rule --add app="^System Settings$" manage=off layer=normal
yabai -m rule --add app="^Archive Utility$" manage=off layer=normal
yabai -m rule --add app="^Discord$" manage=off layer=normal
yabai -m rule --add app="^Cisco AnyConnect Secure Mobility Client$" manage=off layer=normal
yabai -m rule --add app="^zoom.us$" manage=off layer=normal
yabai -m rule --add app="^Native Access$" manage=off layer=normal
yabai -m rule --add app="^Live$" manage=off layer=normal
yabai -m rule --add app="^qemu" manage=off layer=normal
yabai -m rule --add app="^Xcode" manage=off layer=normal
yabai -m rule --add app="^Wave Link" manage=off layer=normal
yabai -m rule --add app="^Install" manage=off layer=normal
yabai -m rule --add app="^Little Arc" manage=off layer=normal
yabai -m rule --add app="^1Password" manage=off layer=normal
yabai -m rule --add app="^Microsoft Teams" manage=off layer=normal
yabai -m rule --add app="Raycast" manage=off layer=normal
yabai -m rule --add app="DeskPad" manage=off layer=normal
yabai -m rule --add app="KeyCastr" manage=off layer=normal
