#! /bin/bash
# This is a demo config to show some of the most important commands more easily.
# This is meant to be changed and configured, as it is intentionally kept sparse.
# For a more advanced configuration example see my dotfiles:
# https://github.com/FelixKratz/dotfiles
source "./colors.sh"
PLUGIN_DIR="$CONFIG_DIR/plugins"

sketchybar --hotload true

##### Bar Appearance #####
# Configuring the general appearance of the bar, these are only some of the
# options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

sketchybar --bar height=32        \
                 blur_radius=30   \
                 position=top     \
                 sticky=off       \
                 padding_left=10  \
                 padding_right=10 \
                 color="0x00000000"

##### Changing Defaults #####
# We now change some default values that are applied to all further items
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

sketchybar --default icon.font="Hack Nerd Font:Bold:17.0"  \
                     icon.color="0xff$TEXT"                \
                     label.font="Hack Nerd Font:Bold:14.0" \
                     label.color="0xff$TEXT"               \
                     padding_left=2                        \
                     padding_right=2                       \
                     label.padding_left=5                  \
                     label.padding_right=5                 \
                     icon.padding_left=5                   \
                     icon.padding_right=5

source ./items/left.sh
setup_left
source ./items/right.sh
setup_right

##### Finalizing Setup #####
# The below command is only needed at the end of the initial configuration to
# force all scripts to run the first time, it should never be run in an item script.

sketchybar --update
