#! /bin/bash
:: default : sketchybar --trigger skhd_mode_changed MODE=default
:: command : sketchybar --trigger skhd_mode_changed MODE=command
:: workspace : sketchybar --trigger skhd_mode_changed MODE=workspace
:: float : sketchybar --trigger skhd_mode_changed MODE=float

alt - space
command
command, workspace, float <escape
default

cmd - tab : skhd -k "f13"

command <w
workspace
command <f
float
command <shift - h : yabai -m window --swap west
command <shift - j : yabai -m window --swap south
command <shift - k : yabai -m window --swap north
command <shift - l : yabai -m window --swap east
command <h : yabai -m window --focus west
command <j : yabai -m window --focus south
command <k : yabai -m window --focus north
command <l : yabai -m window --focus east
command <r : yabai -m space --rotate 90
command <0 : yabai -m window --toggle zoom-fullscreen
skhd -k "escape"
command <t : yabai -m window --toggle float
skhd -k "escape"
command <e : yabai -m window --toggle split
skhd -k "escape"
command <b : yabai -m space --balance
skhd -k "escape"
command <x : yabai -m window --close
skhd -k "escape"
float <ctrl - h : yabai -m window --grid 1:2:0:1:1:1
float <ctrl - l : yabai -m window --grid 1:2:1:1:1:1
float <shift - h : yabai -m window --grid 1:3:0:1:2:1
float <shift - l : yabai -m window --grid 1:3:1:1:2:1
float <h : yabai -m window --grid 1:3:0:1:1:1
float <space : yabai -m window --grid 1:3:1:1:1:1
float <l : yabai -m window --grid 1:3:2:1:1:1
float <return : yabai -m window --grid 1:1:0:0:1:1
workspace <1 : yabai -m space --focus 1
skhd -k "escape"
workspace <2 : yabai -m space --focus 2
skhd -k "escape"
workspace <3 : yabai -m space --focus 3
skhd -k "escape"
workspace <4 : yabai -m space --focus 4
skhd -k "escape"
workspace <5 : yabai -m space --focus 5
skhd -k "escape"
workspace <6 : yabai -m space --focus 6
skhd -k "escape"
workspace <7 : yabai -m space --focus 7
skhd -k "escape"
workspace <8 : yabai -m space --focus 8
skhd -k "escape"
workspace <9 : yabai -m space --focus 9
skhd -k "escape"
workspace <0 : yabai -m space --focus 10
skhd -k "escape"
workspace <shift - 1 : yabai -m window --space 1
skhd -k "escape"
workspace <shift - 2 : yabai -m window --space 2
skhd -k "escape"
workspace <shift - 3 : yabai -m window --space 3
skhd -k "escape"
workspace <shift - 4 : yabai -m window --space 4
skhd -k "escape"
workspace <shift - 5 : yabai -m window --space 5
skhd -k "escape"
workspace <shift - 6 : yabai -m window --space 6
skhd -k "escape"
workspace <shift - 7 : yabai -m window --space 7
skhd -k "escape"
workspace <shift - 8 : yabai -m window --space 8
skhd -k "escape"
workspace <shift - 9 : yabai -m window --space 9
skhd -k "escape"
workspace <shift - 0 : yabai -m window --space 10
skhd -k "escape"
workspace <shift - h : yabai -m window --space prev
skhd -k "escape"
workspace <shift - l : yabai -m window --space next
skhd -k "escape"
workspace <h : yabai -m space --focus prev
workspace <l : yabai -m space --focus next
workspace <c : yabai -m space --create
skhd -k "escape"
workspace <x : yabai -m space --destroy
skhd -k "escape"
